photo_album_homepage:
    path:     /
    defaults: { _controller: PhotoAlbumBundle:Default:index }
carga_datos:
    path: /cargadatos
    defaults: { _controller: PhotoAlbumBundle:Default:create }
verUsuarios:
    path: /usuarios
    defaults: { _controller: PhotoAlbumBundle:Usuarios:verUsuarios }   
crearUsuario:
    path: /usuarios/crear
    defaults: { _controller: PhotoAlbumBundle:Usuarios:crear }
crearAlbum:
    path: /albums/crear
    defaults: { _controller: PhotoAlbumBundle:Default:crear }
    
