photo_album_homepage:
    path:     /
    defaults: { _controller: PhotoAlbumBundle:Default:index }
carga_datos:
    path: /cargadatos
    defaults: { _controller: PhotoAlbumBundle:Default:create }
verUsuarios:
    path: /admin/usuarios
    defaults: { _controller: PhotoAlbumBundle:Usuarios:verUsuarios }   
crearUsuario:
    path: /admin/usuarios/crear
    defaults: { _controller: PhotoAlbumBundle:Usuarios:crear }
crearAlbum:
    path: /albums/crear
    defaults: { _controller: PhotoAlbumBundle:Default:crear }
login_route:
    path:     /login
    defaults: { _controller: PhotoAlbumBundle:Security:login }
login_check:
    path: /login_check
logout:
    path: /logout
registro:
    path: /registro
    defaults: { _controller: PhotoAlbumBundle:Usuarios:altaUsuario }   
editarUsuario:
    path: /admin/usuarios/{id}
    defaults: { _controller: PhotoAlbumBundle:Usuarios:editarUsuario }       
    
