PhotoAlbumBundle\Entity\usuario:
    type: entity
    table: usuarios
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        nombre:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        activo:
            type: integer
            length: 1
        rol:
            type: string
            length: 255    
            

            